---
- name: Playbook | to install httpd server | on the slave Host
  hosts: webserver
  become: true
  tasks:
    - name: installing HTTPD Package
      yum:
        name: httpd
        state: installed
      register: httpd_install_result

    - name: start the installed httpd server
      service:
        name: httpd
        state: started
      register: httpd_start_result

    - debug:
        var: httpd_install_result

    - debug:
        var: httpd_start_result

